### ISSUE TITLE
Understanding kernel point initialization

### ISSUE THREAD

**Issue by beihaifusang** [HuguesTHOMAS/KPConv#102]
Hi Hugues,

Thanks for your great work and the neat open-source code. Yet, I found a bit confusing in understanding the function `kernel_point_optimization_debug`. It is apparently used to initialize the kernel points for each KPConv ops, but it involves a small optimization (gradient descent) after the point initialization, which makes me wonder what its motivation is and how it could help with the model? 

Besides, could you also explain the optimization goal in it?

Thanks a lot!
Best regards.

**Comment by HuguesTHOMAS** [comment]
Hi @beihaifusang,

Thanks for your interest in my work. The idea of the kernel point initialization is that each kernel point can pretty much be placed anywhere, and we can choose any number K. This is, of course, not possible if you follow a grid disposition for the kernel points.

So we would like to have a regular disposition, for any number of kernel points. Following the idea of 3 by 3 kernel in images, I decided to have on kernel point in the center and one layer of kernel points located on a sphere around the center. At this point, the problem is that there is no obvious regular disposition of points on the surface of a sphere.

To tackle this, I decided to use a small optimization problem that you can see as a physics body problem. Each kernel point applies a repulsive force on the other and the center applies an attractive force to avoid divergence. I translate this problem in term of potentials and apply a gradient descent to optimize the positions of the points. In that way You can choose any number of kernel point and they will always cover the sphere nicely, offering a regular kernel disposition.

I hope this answers your question. If you want more details, you can have a look at the supplementary material of the paper.

Best,
Hugues

**Comment by beihaifusang** [comment]
Wow! This is really a clever way to achieve a regular disposition inside a sphere. I was imaging there should be some gird-sampling-like code to achieve this, but you did it in a more natural way.

Thanks for the explanation!
Best,
Liyao

**Comment by HuguesTHOMAS** [comment]
Thanks, if you are interested in that, I also had a way to do it in a volumetric manner, with Lloyd's algorithm. But I chose the potentials eventually (more stable and regular).
