### ISSUE TITLE
Cloud segmentation, reprojection indexing errors

### ISSUE THREAD

**Issue by jerome-caucat** [HuguesTHOMAS/KPConv#13]
Hi,

Thank you for your work, your paper and this project are really interesting.

I am testing the cloud segmentation on some custom dataset.
I encountered some indexing errors related to reprojection.
Branch Master:  5f9ceca

**I had the following error:**
```
TypeError: list indices must be integers or slices, not tuple
```

**With the following lines:**
- utils/tester.py:772
```
probs = self.test_probs[i_test][dataset.test_proj[i_test], :]
```
- utils/tester.py:784
```
pots = dataset.potentials['test'][i_test][dataset.test_proj[i_test]]
```
- utils/trainer.py:806
```
preds = (sub_preds[dataset.validation_proj[i_val]]).astype(np.int32)
```

**I fixed the errors with the following corresponding code:**
- For utils/tester.py:772
```
probs = np.zeros(
        (points.shape[0],
         self.test_probs[i_test].shape[1]),
        dtype=self.test_probs[i_test].dtype)
for pi, pv in enumerate(self.test_probs[i_test]):
    probs[dataset.test_proj[i_test][pi]] = pv
```
- For utils/tester.py:784
```
pots = np.zeros(
        (points.shape[0],),
        dtype=dataset.potentials['test'][i_test].dtype)
for pi, pv in enumerate(dataset.potentials['test'][i_test]):
    pots[dataset.test_proj[i_test][pi]] = pv
```
- For utils/trainer.py:806
```
preds = np.zeros(labels.shape, dtype=np.int32)
for si, sp in enumerate(sub_preds):
    preds[dataset.validation_proj[i_val][si]] = sp
```

Could you confirm I have done the right thing?

**Comment by HuguesTHOMAS** [comment]
Hello @jerome-caucat,

thank you for your interest. I very recently patched the code for this exact error. Before, my code was doing something like your corrections, but it is not a very efficient, nor elegant reprojection. 

In my opinion, you should keep the lines 772, 784, 806 in utils/trainer.py, but change the second part of the `load_subsampled_clouds` method in your dataset class. More specifically, in the file  dataset/Semantic3D.py for example, this is the part from line 353 to 424.

Currently at dataset/Semantic3D.py:387, the projection inds are computed like this

    # Compute projection inds
    proj_inds = np.squeeze(self.input_trees['validation'][i_val].query(points, return_distance=False))
    proj_inds = proj_inds.astype(np.int32)

You should compute some thing like this instead of the old way which was :

    inds = np.squeeze(self.input_trees['validation'][i_val].query(points, return_distance=False))
    proj_inds = [[] for _ in range(self.input_labels['validation'][i_val].shape[0])]
    for o_ind, sub_ind in enumerate(inds):
        proj_inds[sub_ind] += [o_ind]
    proj_inds = np.array([np.array(ind_list, dtype=np.int32) for ind_list in proj_inds])

I hope this helps.
Best,
Hugues

**Comment by jerome-caucat** [comment]
I did not see your last commit, thanks!
