### ISSUE TITLE
Planar occlusion  explanation

### ISSUE THREAD

**Issue by hadilou** [HuguesTHOMAS/KPConv#148]
Hi,

Can you please explain the idea behind the [planar occlusion](https://github.com/HuguesTHOMAS/KPConv/blob/16bfbb96ac9af48a3c829d1f8123152d35b63862/datasets/common.py#L143) augmentation strategy implemented in `datasets/common.py`. I tried to visualize how it works but I wasn't able to. Is it truly used when we set `config.augment_occlusion = 'planar'`?
Thanks in advance

**Comment by HuguesTHOMAS** [comment]
Hi @hadilou,

Actually, this is not a supported feature. This code is research work and contains some stuff that I explored and then abandoned. In this case, I never really used this planar occlusion augmentation. If you want to explore that yourself, the idea was to remove some part of the shapes randomly so that the network is robust to occlusions, but I am not sure the implementation is correct so you might need to modify it.

Best,
Hugues
