### ISSUE TITLE
CPU usage during training.

### ISSUE THREAD

**Issue by XuyangBai** [HuguesTHOMAS/KPConv#22]
Hi @HuguesTHOMAS , I am training KPConv with 4 GPUs and 12 CPUs. However when I run my model it uses almost all the CPUs available even when I specify that I want to use only one thread:
```python
            cProto = tf.ConfigProto(allow_soft_placement=True, 
                                    intra_op_parallelism_threads=1, 
                                    inter_op_parallelism_threads=1, 
                                    device_count={'CPU': 1})
```
And 
```python
    # Number of CPU threads for the input pipeline
    input_threads = 1
```
I use `perf top` to see what those threads are actually doing and find that most of the cpu is taken by `tf_batch_neighbors.so`. 

![屏幕快照 2019-09-18 下午9 33 34](https://user-images.githubusercontent.com/15166089/65153244-00fdf300-da5c-11e9-8471-eaccd6ff439e.png)

It is really wired because the tf_batch_neighbors is called in `tf_classification_inputs` or `tf_segmentation_inputs` function, which is used by `get_tf_mapping`, so I think setting the input_threads to 1 will limit the thread of this operation to be 1. So I wonder is there any methods to limit the CPU usage of this tf module ?

**Comment by HuguesTHOMAS** [comment]
Hi @XuyangBai,

**First some answers to your questions**
I did some experiments to undersand your problem and here is what i found:

- I did not see any effect of the `tf.ConfigProto` class. I assume this class controls the operations of the main graph, which are done on GPU for the most part in our case. It does not the internal parallelism in tf.dataset class.

- The `input_threads` parameters controls the number of threads that run the mapping function like you said, and it effectively limits the thread of this operation to be 1. You can see that if you uncomment the line: 
https://github.com/HuguesTHOMAS/KPConv/blob/5f9cecae72c7a22cc4247b7852eee707ecab8fcd/training_S3DIS.py#L212
the `check_input_pipeline_timing` method runs the input pipeline alone (without network operations on GPU) and you can see that when `input_threads = 1` than when `input_threads = 8`, the CPU load is much lower. It seems to indicate that the mapping function is effectively ran by only 1 thread.

- `tf_batch_neighbors.so` does not use multiple threads internally. Its a a simple C++ function using nanoflann library which is not multi-threaded. The problem seems to come from tf.dataset mapping mechanism. As I explain below

- I did a last experiment to confirm my intuition. I slowed my python generator with `time.sleep` to force my input pipeline to process one input at a time. Whether you use `input_threads = 1` or `input_threads = 8`, as soon as a batch is yielded, multiple threads appear on my CPU. 

**Conclusion**
The `input_threads` variable controls how many input batches are processed simultaneously by the mapping function. However, it seems that more than one thread are used internally for each element. I do not know why tf.dataset have this behavior, but I assume the reason is that was not designed for single thread purposes. It is a tool that is uses mostly to build parallel input queues.

**My advise**
I built the whole architecture around the idea of a parallel input queue, and I did not think of a single thread behavior. In fact the difference with an image network is that we have to compute neighborhoods and this is a heavy load for CPUs, so if you want your GPU to be active at 100%, you need several CPU threads.

From my point of view, if you want to use only one thread of CPU, you have to redesign a new input pipeline that uses placeholders instead of `tf.dataset` class.

**Comment by XuyangBai** [comment]
Thank you so much for your experiment and advise !
