### ISSUE TITLE
Question about sampling strategy and size limit

### ISSUE THREAD

**Issue by yyyooo278** [HuguesTHOMAS/KPConv#28]
Hi!
Thanks for your wonderful paper and code! I'm currently working on it, trying to reproduce the results reported in your work on Semantic3D dataset. Following are two problems I have encountered recently while reading your code.
1.In common.py, function calibrate_batches. I have no problem understanding the first half of this function. But I have trouble understanding the second part, starting from sum_s = 0. Would you please elaborate the ideas behind?
2.In Semantic3D.py, function spatially_regular_gen, you choose spherical samples from point clouds according to randomly-generated potentials, and update the potentials each round so the potential of center point increases the most. Does this sampling technique have a specific name? Besides, what is the advantage of this center point selection technique compared to others, such as uniform grid selection? 
Thank you very much!

**Comment by HuguesTHOMAS** [comment]
Hi @yyyooo278,

Thank you for your interest in KPConv. Here are some clarifications:

1. To understand the function calibrate_batches, you have to understand how our batches are stacked. We do not use batches with a constant number of elements, because the number of points inside each element (the input spheres) vary a lot. Instead we fix a maximum number of point that a batch can contain and stack elements until the limit is reached. Therefore the batches have a more regular sizes: each batch has approximately the same number of points but a different number of input spheres. However we still have a `batch_num` parameter. The role of the function `calibrate_batches` is to calibrate the maximum number of point in a batch (`self.batch_limit`) so that the average number of input spheres contained in a batch is close to `batch_num`.

2. The function `spatially_regular_gen` defines a sampling technique based on updated potentials. I had this idea on my own but I assume similar sampling technique had already been defined (I don't have any idea of the name though). The problem of uniform sampling is that it is biased by the density of points. In a dataset like Semantic3D, with large density variations, random sampling is not recommended. Indeed the parts of the 3D scenes with lower densities will be picked very rarely and the network will only learn the shapes of the high density regions. The main advantage of using potentials is to ensure that every part of the 3D scenes is sampled enough times.

I hope my answers are clear enough, don't hesitate if you have any other questions.

Best,
Hugues
