### ISSUE TITLE
How to prepare the Semantic3D ,  ScanNet and NPM3D dataset ?

### ISSUE THREAD

**Issue by Violetit** [HuguesTHOMAS/KPConv#31]
Hi, @HuguesTHOMAS 
Thank you for sharing this wonderful work !

I am wondering about the datasets' preparation, what exactly the  the Semantic3D ,  ScanNet and NPM3D looks like under the directory `/KPConv/Data/`  ?  How to organize them?

**Comment by HuguesTHOMAS** [comment]
Hi @Violetit,

These datasets have different organizations at the origin, which makes their directories in `/KPConv/Data/` a bit different. Lets take Semantic3D as an example. If you follow the instruction in [the scene segmentation guide](https://github.com/HuguesTHOMAS/KPConv/blob/master/doc/scene_segmentation_guide.md#scene-segmentation-on-semantic3d), your folder should originally look like this:
- Semantic3D 
  - original_data
    - bildstein_station1_xyz_intensity_rgb.labels
    - bildstein_station1_xyz_intensity_rgb.txt
    - bildstein_station3_xyz_intensity_rgb.labels
    - bildstein_station3_xyz_intensity_rgb.txt
    - ...
    - MarketplaceFeldkirch_Station4_rgb_intensity-reduced.txt
    - StGallenCathedral_station6_rgb_intensity-reduced.txt
    - ...

The preparation script will then create `.ply` files from these text files and store them in the folders `/Semantic3D/ply_full/` and `/Semantic3D/ply_subsampled/`. For this particular dataset the training point clouds are subsampled and the test cloud are kept intact. This is because the training scenes have very high densities close to the scanner and we dont need so many points for the classification. For test, we need the original points to be able to submit results. But the test scenes of "reduced-8" challenge are already subsampled anyway.

Eventually when a training is started with certain parameters. The input point clouds are subsampled again to match the `first_subsampling_dl` parameter. These subsampled input clouds are saved in `/Semantic3D/input_X.XXX/` (where dl = X.XXX) for later use.

The organizations for ScanNet and NPM3D folders are approximately the same as Semantic3D, with the original data being different.

Scannet should originally look like this:

- Scannet
  - scans
    - scene0000_00
    - scene0000_01
    - ...
  - scans_test
    - scene0707_00
    - scene0708_00
    - ...

The preparation script will then create the folders `/Scannet/test_meshes`, `/Scannet/test_points`, `/Scannet/training_meshes` and `/Scannet/training_points`

NPM3D should originally look like this:

- NPM3D
  - test_points
    - ajaccio2.ply
    - ajaccio57.ply
    - ...
  - training_points
    - Lille1_1.ply
    - Lille1_2.ply
    - ...

**Comment by anovoam** [comment]
Hi @HuguesTHOMAS 

Thank you for your amazing work. I was wondering if you could help me with an issue regarding the Semantic3D code.

The folder `/Semantic3D/ply_full/ `was not created but `/Semantic3D/input_0.060/ `did (with no subfolders). I changed in the training process `ply_full `to `ply_subsampled` in case this was a mistake, as the name of the file was inside this. 
With this, the code did train the data but in the `test_any_model.py` I find this error again and I was wondering if I should manually add this folder, as I cannot find its definition in the code.

Thank you in advance

**Comment by HuguesTHOMAS** [comment]
Hi @anovoam,

There was indeed a mistake in the code. The folder `/Semantic3D/ply_full/` should be created so that the prediction can be reprojected to the original points. The error was just in the name of the test_folder. It should be `'ply_full/reduced-8'` instead of `'ply_subsampled/reduced-8'`

I just modified the code it should work now.

Best,
Hugues
