### ISSUE TITLE
Effect on convolution of padding point clouds

### ISSUE THREAD

**Issue by no-materials** [HuguesTHOMAS/KPConv#47]
Greetings @HuguesTHOMAS , in my extension of KPConv for partial point cloud completion it is necessary for the point clouds to be padded (via duplicating certain random existing points) in order for them to have a specific number of points.
I am doing this *after* the grid subsampling preprocess step of the current implementation. My question is: do you believe this will affect the feature extraction of the kernel point convolutions negatively  in any way?

**Comment by HuguesTHOMAS** [comment]
Hi @no-materials,

Yes, padding point cloud will have an effect on the feature extraction, if you do not handle them properly. A point that appears two times, will count two times in the feature extraction process. If you want to negate this effect, you have to assign these new duplicates a feature equal to zeros. In that case, they will be "invisible" for the convolution, exactly like the shadow points that we already use.

Another thing is that having two points with the exact same position is not a good idea. Some of the operations in our network are based on distance and the gradient of distance is not defined when distance is equal to zero. This can lead to NaN values in the features. I would advise to add a small random noise to your duplicates so that you avoid any problem like that.

Best,
Hugues

**Comment by no-materials** [comment]
I see! Thanks for the heads up!
