### ISSUE TITLE
Question for the difference between the the KPFCNN  and KPCNN

### ISSUE THREAD

**Issue by csuzhuzhuxia** [HuguesTHOMAS/KPConv#51]
Hi, @HuguesTHOMAS 
Thank you for your code share!
When i try to use the  Modelnet40 dataset for the segmentation not classfication ,I use KPFCNN model ,but it shows the error,
```
Traceback (most recent call last):
  File "/home/culturerelics/zhurunsong_code/KPConv/training_ModelNet40.py", line 214, in <module>
    model = KernelPointFCNN(dataset.flat_inputs, config)
  File "/home/culturerelics/zhurunsong_code/KPConv/models/KPFCNN_model.py", line 83, in __init__
    self.inputs['out_batches'] = flat_inputs[ind]
IndexError: tuple index out of range
```
can you help me ? thank you!

**Comment by HuguesTHOMAS** [comment]
Hi @csuzhuzhuxia,

ModelNet40 has no segmentation annotation, so you cannot use this dataset for segmentation.

If you have your own annotations, then you have to rewrite a new ModelNet40segmentation class in the `dataset` folder

Best,
Hugues

**Comment by csuzhuzhuxia** [comment]
thank you for you reply!
I try to use the KPFCNN  for the modelnet40 to predict the normal of each point,not for the segmentation lable.and i  find the "flat-input" size is not suiltable.can you tell me how to change the flat-input if i want to do this?

Traceback (most recent call last):
  File "/home/culturerelics/zhurunsong_code/KPConv/training_ModelNet40.py", line 214, in <module>
    model = KernelPointFCNN(dataset.flat_inputs, config)
  File "/home/culturerelics/zhurunsong_code/KPConv/models/KPFCNN_model.py", line 83, in __init__
    self.inputs['out_batches'] = flat_inputs[ind]
IndexError: tuple index out of range

**Comment by HuguesTHOMAS** [comment]
Hi @csuzhuzhuxia,

The "flat_input" is the list of input for the network. It is different between a KP-CNN and a KP-FCNN because the first is a classification network and the second is a segmentation network.

In your case you need a segmentation network because you want to predict the normal at each point. So you need to use the same kind of "flat_input" as the one use for ShapeNetPart segmentation.

In addition, you need to modify several part of the code because the normal prediction is a regression problem and not a classification problem. The head of the network need to be changed. You can create a new "regression_head" in `models/network_blocks.py`. Then you have to addapt the rest of the code to this new head. The ground truth input will not have the same dimension as for a classification problem etc...

**Comment by csuzhuzhuxia** [comment]
thank you !
