### ISSUE TITLE
Questions about Pretrained model and semanticKitti

### ISSUE THREAD

**Issue by shuxu** [HuguesTHOMAS/KPConv#53]
Hi @HuguesTHOMAS 
Thanks for sharing you code,I have two questions.
Firstly,I have test the pretrained model of NPM3D on val and I found the miou is 0.92.But when I train a model using "training_NPM3D.py",and test it  on val, I found the miou is just 0,87,so why the pretrained model that got from the github is much better than my trained model?
Secondly,I notice that you have got a SOTA result on semanticKITTI competition,I'm very interested with it,will you sharing you code again?

Best,
xu

**Comment by HuguesTHOMAS** [comment]
Hi @shuxu,

For your first question, did you use the same parameters as the pretrained model? At least
    
    first_subsampling_dl = 0.04
    in_radius = 2.0

instead of 

    first_subsampling_dl = 0.08
    in_radius = 4.0

For your second question, I did not implement it very well, just a fast test to see the performances on such dataset. I might share the code in the future, but it would be quite some work to clean it and right now I have other priorities.

If you really want the code and you are not afraid of digging into it (with the only help of some comments I wrote), I can share it with you by email.

Best,
Hugues

**Comment by fanyang587** [comment]
Could you please share the code and information about semantic-kitti to me too? Thanks.

**Comment by ecr23xx** [comment]
Could you please share the code and information about semantic-kitti to me too? Thanks.

**Comment by phil0stine** [comment]
> If you really want the code and you are not afraid of digging into it 

Not afraid :)

**Comment by HuguesTHOMAS** [comment]
Hi all,

Given that many people are asking for it I will upload the code for semantickitti, even if its is not very clean and kind off buggy.

**Comment by HuguesTHOMAS** [comment]
See the code [here](https://drive.google.com/open?id=12npkHHnqzhhl5i-2q_RD-Cw_urUdWC0J).

**Comment by amiltonwong** [comment]
@HuguesTHOMAS , Thanks a lot for your kind help :)
