### ISSUE TITLE
Padding in tf_stack_batch_inds

### ISSUE THREAD

**Issue by nejcd** [HuguesTHOMAS/KPConv#55]
Hi Hugues,

I have a question regarding padding in common.py tf_stack_batch_inds. 

https://github.com/HuguesTHOMAS/KPConv/blob/e793033a586a3f5eb55566633f1f9fe5fac95fab/datasets/common.py#L446-L449

So if I understand correctly the code above in case that point cloud in batch (PC) is smaller than the largest PC in batch then you pad the indices as they have to be equal dimensions. These indices are used then to get individual PC as they are all stacked in the same axis. In this code, you pad the indices with the largest index of the batch, meaning that all PCs that are smaller then-largest will gather also points from the wrong PC (basically last point)?

--- Example
**Stacked_Points = [P0, P0, P1, P1, P1]**     
Where  **P**_i_ are points belonging  to the corresponding  point cloud i

**stacked_batch_indicies = [[0,1,4],[2,3,4]]**

Meaning that if we call _tf.gather(Stacked_Points, stacked_batch_indicies)_ we get ->
[[P0, P0, **P1(5th)**],
[P1, P1, P1]]

Do I understand this part of code correctly or am I missing something?

Thanks, best,
Nejc

**Comment by HuguesTHOMAS** [comment]
Hi @nejcd,

Your understanding is nearly correct except one detail. We do not pad the indices with the largest index of the batch `num_points - 1`, we pad the indices with `num_points`, which points to nothing. 

In your example
Stacked_Points = [P0, P0, P1, P1, P1]
stacked_batch_indicies = [[0,1,5],[2,3,4]]

Meaning that if we call tf.gather(Stacked_Points, stacked_batch_indicies) we get ->
[[P0, P0, ??],
[P1, P1, P1]]

?? is a "shadow point". It should raise an error because the indice points nowhere. But in fact, before we call tf.gather to collect the features, we add a supplementary feature equal to zero. Therefore all the "shadow point" get a feature equal to zero, which is equivalent to empty space. They thus do not exist for the network, and everything works well.

I hope I was clear enough.

Best,
Hugues

**Comment by nejcd** [comment]
Hi, @HuguesTHOMAS  thanks for the reply. 

It is clear now. 

Best,
Nejc
