### ISSUE TITLE
Strange result of S3DIS

### ISSUE THREAD

**Issue by YoungSun3Pan** [HuguesTHOMAS/KPConv#56]
@HuguesTHOMAS Thanks for your codes. When i test on area5 of S3DIS, we found it got 0.0 miou  in the category of beam, but there are 4 beam instances on area5 .

![result](https://user-images.githubusercontent.com/53615521/72240508-52d81380-361f-11ea-9f57-9141f600c263.JPG)

**Comment by HuguesTHOMAS** [comment]
Hi @YoungSun3Pan,

This is completely normal. Like any dataset, S3DIS is not perfect. In particular, the beam class is not well defined at all. In Area5, the beam instances are unique because they are all inclined as shown is the two following images:
![Sanstitre](https://user-images.githubusercontent.com/16581582/72251368-1516c300-35fe-11ea-93ab-9ddf0dd4c939.png)
![Sanstitre2](https://user-images.githubusercontent.com/16581582/72251375-1942e080-35fe-11ea-8375-303bbc43e28b.png)

In the rest of the training set, all beams are horizontal as shown here:
![Sanstitre3](https://user-images.githubusercontent.com/16581582/72251440-3677af00-35fe-11ea-889c-7e250f43a6b5.png)

If you get a score higher than 0%, it could nearly be considered as a mistake in that situation. Anyway this is just a class that you should ignore.
