### ISSUE TITLE
Question about multi-scale process

### ISSUE THREAD

**Issue by xuye-z** [HuguesTHOMAS/KPConv#69]
Hi Hugues,
Thanks for your outstanding work, it helps a lot to me!
I am new to point cloud segmentation. When i worked on image segmentation, it usually works when using convolution kernels of different size in the network to get multi-scale receptive field and capture multi-scale features. So does this strategy also works in point cloud segmentation?

**Comment by HuguesTHOMAS** [comment]
Hi @xuye-z,

The answer to this question is not trivial. We can say that adding differents kernel sizes could help, but it has to be done right. For example atrous convolutions like in image would probably not increase the performances that much in my opinion. The reason is that point clouds are sparse and if you use atrous convolution, they wont "see" many points (this problem does not exist in images because they are dense). This is exactly why deformable convolutions are promising in my opinion, as they fit the input point cloud.

I hope this answers your question.
Best,
Hugues

**Comment by xuye-z** [comment]
thanks for your quick reply, it really helps!
I noticed that the output_loss is a simple softmax_cross_entropy_loss without any weighting strategy. Does it make any sense to use weighted loss(for example, weighted ce loss, focal loss, etc...) when segmenting imbalanced data?
