### ISSUE TITLE
cant find -ltensorflow_framework

### ISSUE THREAD

**Issue by zhouhao957** [HuguesTHOMAS/KPConv#79]
Hello, your article is wonderful. But when I'm running
sh compile_op.sh
The following error occurs：

/usr/bin/ld: cant find -ltensorflow_framework
collect2: error: ld returned 1 exit status

I didn't change anything. Could you give me some Suggestions？

**Comment by j2oj2o** [comment]
I had a similar problem which was compounded by having no su access.  I got around your problem by (I am not saying it is the best solution):

1) locating the missing file using:

find / -name "libtensorflow_framework.so" 2> /dev/null

Mine found a so.2 file

2) Create a soft link in the tf_custom_ops folder which points to the file in question:

ln -s /mnt/storage/software/languages/anaconda/Anaconda3-2019.10-tflow-2.1.0/lib/python3.7/site-packages/tensorflow_core/libtensorflow_framework.so.2 libtensorflow_framework.so

3) Change the compile_op.sh to add the tf_custom_ops folder as a library source.
i) Added TF_LIB2='/path to/KPConv/tf_custom_ops' near the top of the script
AND
ii) changed -L$TF_LIB to -L$TF_LIB -L$TF_LIB2 for each of the four compilation instructions.

**Comment by zhouhao957** [comment]
Hello @j2oj2o 
Your answer solved my difficulty. However, I have encountered the following errors：
`... ...
 
Dataset Preparation
*******************
Preparing ply files
Done in 0.1s
Loading training points
397.4 MB loaded in 0.5s
Loading test points
82.0 MB loaded in 0.1s
Initiating input pipelines
WARNING: Logging before flag parsing goes to stderr.
W0531 13:23:31.021588 140689917622016 deprecation.py:323] From /home/dell/wag-gpu/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py:494:py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
2020-05-31 13:23:31.084677: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2020-05-31 13:23:31.105487: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Quadro P4000 major: 6 minor: 1 memoryClockRate(GHz): 1.48
pciBusID: 0000:b3:00.0
2020-05-31 13:23:31.105753: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2020-05-31 13:23:31.107385: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2020-05-31 13:23:31.108510: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2020-05-31 13:23:31.108834: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2020-05-31 13:23:31.110571: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2020-05-31 13:23:31.111638: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2020-05-31 13:23:31.115243: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2020-05-31 13:23:31.116396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

Could you give me some advice again? Thank you very much.

**Comment by j2oj2o** [comment]
Hi @zhouhao957 

Unfortunately "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`" could mean a lot of things.

**The most comprehensive way to determine the problem is to debug it.  See https://wiki.python.org/moin/DebuggingWithGdb**

Personally, I would assume it is some kind of memory issue (even though the output did not show any OOM - out of memory errors).  In particular I have found increasing **first_subsampling_dl** will reduce the size of the subsequent ply files and also lowering the **batch_num** value will also reduce the memory footprint.  These are simple ways to test the water.

I would also consider changing from GPU to CPU by changing **on_CPU = False** to **on_CPU = True** in the trainer.py or tester.py file.  Other things to try are to ensure you are using the same Tensorflow and Python versions as the code was tested.

Admittedly, none of the above modifications are necessarily going to solve your problem but they may give you an idea of where to start looking.

**Comment by HuguesTHOMAS** [comment]
Thanks @j2oj2o for your details answer.

In my case I sometimes had the `cant find -ltensorflow_framework` error when using docker or virtual environments. If you have tensorflow installed in a virtual env, you need to activate it when compiling the tf_ops. 

Concerning the `SIGSEGV` error, the suggestions from @j2oj2o are all really smart to help debugging. I can also advice to go to reduce the number of input threads to 1 so that you can track the error more easily. Also you can comment the lines that fix the prefetch size. For example 
https://github.com/HuguesTHOMAS/KPConv/blob/132fdc628fb4850548e931c8b02c6325e7cac85e/datasets/common.py#L582
This will cancel the input pipeline parallele queues

I also need to ask, what version of python/cuda/tensorflow you are using.

**Comment by zhouhao957** [comment]
Thank you for your answer @HuguesTHOMAS @j2oj2o 
## 1.    
version:  python3.5.      cuda10.1.105   tendorflow1.14.0
Sorry, I know my version doesn't meet the requirements.
## 2.  
 Ask  again，
WARNING:` Logging before flag parsing goes to stderr.
W0531 13:23:31.021588 140689917622016 deprecation.py:323] From /home/dell/wag-gpu/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py:494:py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
options available in V2.

This warning has no effect, I don’t need to change it, right?

 Thanks again

**Comment by HuguesTHOMAS** [comment]
I never had this warning, but I assume that it has no effect indeed
