### ISSUE TITLE
Question about Convolution ops

### ISSUE THREAD

**Issue by XuyangBai** [HuguesTHOMAS/KPConv#8]
Hi, Thank you for your sharing. I read the code about the function `KPConv` and `KPConv_ops` in `convolution_ops.py` and I found that the convolution operation defined in these two functions are for one single point cloud input, so how is the case when I am trying to input a a batch of point cloud since these point cloud fragments may have different number of points ?

**Comment by HuguesTHOMAS** [comment]
Hi @XuyangBai,

As explained in the supplementary of the paper:

> Our layers process point clouds of variable sizes, so we cannot stack them along a new “batch” dimension. We thus stack our point and feature tensors along their first dimension (number of points).

Therefore the implementation does not change if the convolution processes a batch or a single point cloud. This trick (also used in the [Monte Carlo Convolution Paper](https://arxiv.org/abs/1806.01759)) is quite elegant and works because the neighbor and pooling indices do not point from one cloud to another inside the batch. Each cloud of the batch is thus processed independently. as if it was alone.

I hope this explanation is clear enough.
Best,
Hugues

**Comment by XuyangBai** [comment]
Hi @HuguesTHOMAS 

Thanks a lot for your explanation. That really makes sense to me !
